/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param participants List of participants
 */


data class AddRemoveParticipantsRequest (

    /* List of participants */
    @Json(name = "participants")
    val participants: kotlin.collections.List<kotlin.String>? = null

)

