/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.APIGroup
import io.inappchat.sdk.models.APIMessage
import io.inappchat.sdk.models.APIUser
import io.inappchat.sdk.models.EncryptionKey

import com.squareup.moshi.Json

/**
 * 
 *
 * @param threadId Thread ID
 * @param threadType Type of thread - single/group
 * @param createdAt Therad object creation time
 * @param participants array of read timestamps
 * @param user 
 * @param group 
 * @param lastMessage 
 * @param e2eEncryptionKeys 
 */


data class APIThread (

    /* Thread ID */
    @Json(name = "threadId")
    val threadId: kotlin.String,

    /* Type of thread - single/group */
    @Json(name = "threadType")
    val threadType: APIThread.ThreadType,

    /* Therad object creation time */
    @Json(name = "createdAt")
    val createdAt: java.math.BigDecimal,

    /* array of read timestamps */
    @Json(name = "participants")
    val participants: kotlin.collections.List<APIUser>,

    @Json(name = "user")
    val user: APIUser? = null,

    @Json(name = "group")
    val group: APIGroup? = null,

    @Json(name = "lastMessage")
    val lastMessage: APIMessage? = null,

    @Json(name = "e2eEncryptionKeys")
    val e2eEncryptionKeys: kotlin.collections.List<EncryptionKey>? = null

) {

    /**
     * Type of thread - single/group
     *
     * Values: string,group
     */
    enum class ThreadType(val value: kotlin.String) {
        @Json(name = "string") string("string"),
        @Json(name = "group") group("group");
    }
}

