/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.AvailabilityStatus

import com.squareup.moshi.Json

/**
 * 
 *
 * @param eRTCUserId Unique ID of the user
 * @param appUserId Email address
 * @param name Name of user
 * @param profilePic User Profile Picture. Prepond base userServer URL to generate complete path. eg. http://global.ripbullertc.com/v1/
 * @param profilePicThumb User Profile Picture Thumb Image
 * @param profileStatus User Profile Status
 * @param phoneNumber User phone number
 * @param loginTimeStamp Epoch Time Stamp of last Login
 * @param availabilityStatus 
 */


data class APIUser (

    /* Unique ID of the user */
    @Json(name = "eRTCUserId")
    val eRTCUserId: kotlin.String,

    /* Email address */
    @Json(name = "appUserId")
    val appUserId: kotlin.String,

    /* Name of user */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* User Profile Picture. Prepond base userServer URL to generate complete path. eg. http://global.ripbullertc.com/v1/ */
    @Json(name = "profilePic")
    val profilePic: kotlin.String? = null,

    /* User Profile Picture Thumb Image */
    @Json(name = "profilePicThumb")
    val profilePicThumb: kotlin.String? = null,

    /* User Profile Status */
    @Json(name = "profileStatus")
    val profileStatus: kotlin.String? = null,

    /* User phone number */
    @Json(name = "phoneNumber")
    val phoneNumber: kotlin.String? = null,

    /* Epoch Time Stamp of last Login */
    @Json(name = "loginTimeStamp")
    val loginTimeStamp: kotlin.Int? = null,

    @Json(name = "availabilityStatus")
    val availabilityStatus: AvailabilityStatus? = null

)

