/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param accessToken The auth0 access token
 * @param email User ID based on loginType
 * @param deviceId Unique device id. For example, UDID for ios
 * @param picture A profile picture URL
 * @param name A display name
 * @param nickname A nickname
 * @param deviceType Type of device i.e. android or ios. Allowed valies android/ios
 * @param fcmToken FCM regsitration token. Optional.
 * @param apnsToken the device APNS token
 */


data class Auth0LoginInput (

    /* The auth0 access token */
    @Json(name = "accessToken")
    val accessToken: kotlin.String,

    /* User ID based on loginType */
    @Json(name = "email")
    val email: kotlin.String,

    /* Unique device id. For example, UDID for ios */
    @Json(name = "deviceId")
    val deviceId: kotlin.String,

    /* A profile picture URL */
    @Json(name = "picture")
    val picture: kotlin.String? = null,

    /* A display name */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* A nickname */
    @Json(name = "nickname")
    val nickname: kotlin.String? = null,

    /* Type of device i.e. android or ios. Allowed valies android/ios */
    @Json(name = "deviceType")
    val deviceType: Auth0LoginInput.DeviceType? = null,

    /* FCM regsitration token. Optional. */
    @Json(name = "fcmToken")
    val fcmToken: kotlin.String? = null,

    /* the device APNS token */
    @Json(name = "apnsToken")
    val apnsToken: kotlin.String? = null

) {

    /**
     * Type of device i.e. android or ios. Allowed valies android/ios
     *
     * Values: android,ios
     */
    enum class DeviceType(val value: kotlin.String) {
        @Json(name = "android") android("android"),
        @Json(name = "ios") ios("ios");
    }
}

