/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.APIUser
import io.inappchat.sdk.models.NotificationSettings
import io.inappchat.sdk.models.Token

import com.squareup.moshi.Json

/**
 * An auth response
 *
 * @param token 
 * @param user 
 * @param notificationSettings 
 */


data class Auth (

    @Json(name = "token")
    val token: Token,

    @Json(name = "user")
    val user: APIUser,

    @Json(name = "notificationSettings")
    val notificationSettings: NotificationSettings? = null

)

