/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * availability status of user. i.e. online/away/invisible/dnd
 *
 * Values: online,away,invisible,dnd,offline
 */

enum class AvailabilityStatus(val value: kotlin.String) {

    @Json(name = "online")
    online("online"),

    @Json(name = "away")
    away("away"),

    @Json(name = "invisible")
    invisible("invisible"),

    @Json(name = "dnd")
    dnd("dnd"),

    @Json(name = "offline")
    offline("offline");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is AvailabilityStatus) "$data" else null

        /**
         * Returns a valid [AvailabilityStatus] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): AvailabilityStatus? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

