/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.AvailabilityStatus

import com.squareup.moshi.Json

/**
 * A user's availability changed
 *
 * @param eRTCUserId The user ID
 * @param availabilityStatus 
 */


data class AvailabilityEvent (

    /* The user ID */
    @Json(name = "eRTCUserId")
    val eRTCUserId: kotlin.String,

    @Json(name = "availabilityStatus")
    val availabilityStatus: AvailabilityStatus

)

