/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param eRTCUserId eRTCUserId
 * @param appUserId appUserId
 */


data class BaseMsgResponderSchema (

    /* eRTCUserId */
    @Json(name = "eRTCUserId")
    val eRTCUserId: kotlin.String? = null,

    /* appUserId */
    @Json(name = "appUserId")
    val appUserId: kotlin.String? = null

)

