/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.BaseMsgResponderSchema

import com.squareup.moshi.Json

/**
 * 
 *
 * @param numOfReplies Number of replies on this chat
 * @param responderList List of the responders on this chat
 */


data class BaseChatReplyThreadDataSchema (

    /* Number of replies on this chat */
    @Json(name = "numOfReplies")
    val numOfReplies: java.math.BigDecimal? = null,

    /* List of the responders on this chat */
    @Json(name = "responderList")
    val responderList: kotlin.collections.List<BaseMsgResponderSchema>? = null

)

