/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param appUserId appUserId of user
 */


data class BlockUnblockUserRequest (

    /* appUserId of user */
    @Json(name = "appUserId")
    val appUserId: kotlin.String? = null

)

