/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param joined Get groups user have joined
 * @param groupType Public or private group
 */


data class ChannelQuery (

    /* Get groups user have joined */
    @Json(name = "joined")
    val joined: kotlin.Boolean? = null,

    /* Public or private group */
    @Json(name = "groupType")
    val groupType: ChannelQuery.GroupType? = null

) {

    /**
     * Public or private group
     *
     * Values: `public`,`private`
     */
    enum class GroupType(val value: kotlin.String) {
        @Json(name = "public") `public`("public"),
        @Json(name = "private") `private`("private");
    }
}

