/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.E2eKeyObjWithReturnCodee

import com.squareup.moshi.Json

/**
 * 
 *
 * @param returnCode return code for e2e encrypted chat request. It can be senderKeyValidityExpired (new key to be provided in keyList, also new device key if there) / receiverKeyValidationError / senderNewDeviceKeyAvailable (new device key to be provided in keyList, also same device key if validity expired) / success
 * @param retryRequired Boolean parameter which indicates if same chat needs to be re-sent after resolving issues based on returnCode
 * @param keyList list of key details based on returnCode. Details of this list depends on returnCode.
 */


data class ChatStatusSchema (

    /* return code for e2e encrypted chat request. It can be senderKeyValidityExpired (new key to be provided in keyList, also new device key if there) / receiverKeyValidationError / senderNewDeviceKeyAvailable (new device key to be provided in keyList, also same device key if validity expired) / success */
    @Json(name = "returnCode")
    val returnCode: kotlin.String? = null,

    /* Boolean parameter which indicates if same chat needs to be re-sent after resolving issues based on returnCode */
    @Json(name = "retryRequired")
    val retryRequired: kotlin.Boolean? = null,

    /* list of key details based on returnCode. Details of this list depends on returnCode. */
    @Json(name = "keyList")
    val keyList: kotlin.collections.List<E2eKeyObjWithReturnCodee>? = null

)

