/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * channel Admin Status
 *
 * @param status status of report (new/reportConsidered, reportIgnored)
 * @param createdAt Chat Report Status creation epoch timeStamp
 * @param category Category of chat Report
 */


data class ChatReportSchemaChannelAdminStatus (

    /* status of report (new/reportConsidered, reportIgnored) */
    @Json(name = "status")
    val status: kotlin.String? = null,

    /* Chat Report Status creation epoch timeStamp */
    @Json(name = "createdAt")
    val createdAt: java.math.BigDecimal? = null,

    /* Category of chat Report */
    @Json(name = "category")
    val category: kotlin.String? = null

)

