/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.ChatReportEventEvent

import com.squareup.moshi.Json

/**
 * Chat report updated event
 *
 * @param chatReportId 
 * @param event 
 */


data class ChatReportEvent (

    @Json(name = "chatReportId")
    val chatReportId: kotlin.String? = null,

    @Json(name = "event")
    val event: ChatReportEventEvent? = null

)

