/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.ChatStatusKeyListInner
import io.inappchat.sdk.models.SenderReturnCode

import com.squareup.moshi.Json

/**
 * 
 *
 * @param returnCode 
 * @param retryRequired 
 * @param keyList 
 */


data class ChatStatus (

    @Json(name = "returnCode")
    val returnCode: SenderReturnCode,

    @Json(name = "retryRequired")
    val retryRequired: kotlin.Boolean,

    @Json(name = "keyList")
    val keyList: kotlin.collections.List<ChatStatusKeyListInner>

)

