/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.ChatSearchQueryObj

import com.squareup.moshi.Json

/**
 * 
 *
 * @param searchQuery 
 * @param resultCategories Result category list
 */


data class ChatSearchRequest (

    @Json(name = "searchQuery")
    val searchQuery: ChatSearchQueryObj? = null,

    /* Result category list */
    @Json(name = "resultCategories")
    val resultCategories: kotlin.collections.List<kotlin.String>? = null

)

