/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.ChatMultipleResponseObj

import com.squareup.moshi.Json

/**
 * 
 *
 * @param results list of individual chat response
 */


data class ChatMultiplePost200ResponseResult (

    /* list of individual chat response */
    @Json(name = "results")
    val results: kotlin.collections.List<ChatMultipleResponseObj>? = null

)

