/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.ChatReportUpdatedEventEventDataChatReportChannelAdminStatus
import io.inappchat.sdk.models.ChatReportUpdatedEventEventDataChatReportChat
import io.inappchat.sdk.models.ChatReportUpdatedEventEventDataChatReportReporterERTCUser
import io.inappchat.sdk.models.ChatReportUpdatedEventEventDataChatReportTenantAdminStatus

import com.squareup.moshi.Json

/**
 * 
 *
 * @param createdAt 
 * @param tenantId 
 * @param category 
 * @param reason 
 * @param channelAdminStatus 
 * @param tenantAdminStatus 
 * @param reporterERTCUser 
 * @param chat 
 */


data class ChatReportUpdatedEventEventDataChatReport (

    @Json(name = "createdAt")
    val createdAt: java.math.BigDecimal,

    @Json(name = "tenantId")
    val tenantId: kotlin.String,

    @Json(name = "category")
    val category: kotlin.String,

    @Json(name = "reason")
    val reason: kotlin.String,

    @Json(name = "channelAdminStatus")
    val channelAdminStatus: ChatReportUpdatedEventEventDataChatReportChannelAdminStatus,

    @Json(name = "tenantAdminStatus")
    val tenantAdminStatus: ChatReportUpdatedEventEventDataChatReportTenantAdminStatus,

    @Json(name = "reporterERTCUser")
    val reporterERTCUser: ChatReportUpdatedEventEventDataChatReportReporterERTCUser,

    @Json(name = "chat")
    val chat: ChatReportUpdatedEventEventDataChatReportChat

)

