/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param appUserId 
 * @param name 
 */


data class ChatReportUpdatedEventEventDataChatReportReporterERTCUser (

    @Json(name = "appUserId")
    val appUserId: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String

)

