/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.ChatReportUpdatedEventEventData

import com.squareup.moshi.Json

/**
 * 
 *
 * @param eventType 
 * @param eventData 
 */


data class ChatReportUpdatedEvent (

    @Json(name = "eventType")
    val eventType: kotlin.String,

    @Json(name = "eventData")
    val eventData: ChatReportUpdatedEventEventData

)

