/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.ReplyThreadSchemaChatRequest

import com.squareup.moshi.Json

/**
 * 
 *
 * @param msgUniqueId message unique ID
 * @param message Modified message string. Applicable for only edit chat.
 * @param replyThreadFeatureData 
 */


data class ChatObjIndeleteChatResponse (

    /* message unique ID */
    @Json(name = "msgUniqueId")
    val msgUniqueId: kotlin.String? = null,

    /* Modified message string. Applicable for only edit chat. */
    @Json(name = "message")
    val message: kotlin.String? = null,

    @Json(name = "replyThreadFeatureData")
    val replyThreadFeatureData: ReplyThreadSchemaChatRequest? = null

)

