/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param keywords List of keywords
 * @param actionType Type of action on match
 */


data class ChatSettingsSchemaDomainFilterInner (

    /* List of keywords */
    @Json(name = "keywords")
    val keywords: kotlin.collections.List<kotlin.String>? = null,

    /* Type of action on match */
    @Json(name = "actionType")
    val actionType: kotlin.String? = null

)

