/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.ChatUserDetailsSchemaStatusDetails

import com.squareup.moshi.Json

/**
 * individual chatUser details
 *
 * @param appUserId appUserId of user
 * @param eRTCUserId eRTC user ID of user
 * @param statusDetails 
 */


data class ChatUserDetailsSchema (

    /* appUserId of user */
    @Json(name = "appUserId")
    val appUserId: kotlin.String? = null,

    /* eRTC user ID of user */
    @Json(name = "eRTCUserId")
    val eRTCUserId: kotlin.String? = null,

    @Json(name = "statusDetails")
    val statusDetails: ChatUserDetailsSchemaStatusDetails? = null

)

