/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param threadId 
 * @param tenantId 
 * @param createdAt 
 */


data class ChatReportUpdatedEventEventDataChatReportChat (

    @Json(name = "threadId")
    val threadId: kotlin.String,

    @Json(name = "tenantId")
    val tenantId: kotlin.String,

    @Json(name = "createdAt")
    val createdAt: java.math.BigDecimal

)

