/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param text Query string. Reuiqred.
 * @param threadId Thread Id if search target is particular thread. optional.
 */


data class ChatSearchQueryObj (

    /* Query string. Reuiqred. */
    @Json(name = "text")
    val text: kotlin.String? = null,

    /* Thread Id if search target is particular thread. optional. */
    @Json(name = "threadId")
    val threadId: kotlin.String? = null

)

