/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param msgUniqueId message unique ID
 */


data class ChatObjIndeleteChatRequest (

    /* message unique ID */
    @Json(name = "msgUniqueId")
    val msgUniqueId: kotlin.String? = null

)

