/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.ChatSettingsDomainFilterInner
import io.inappchat.sdk.models.ChatSettingsProfanityFilterInner

import com.squareup.moshi.Json

/**
 * 
 *
 * @param tenantId Tenant id
 * @param profanityFilter List of profanity filters
 * @param domainFilter List of domain filters
 */


data class ChatSettings (

    /* Tenant id */
    @Json(name = "tenantId")
    val tenantId: kotlin.String? = null,

    /* List of profanity filters */
    @Json(name = "profanityFilter")
    val profanityFilter: kotlin.collections.List<ChatSettingsProfanityFilterInner>? = null,

    /* List of domain filters */
    @Json(name = "domainFilter")
    val domainFilter: kotlin.collections.List<ChatSettingsDomainFilterInner>? = null

)

