/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.ChatSearchResultCategoryObj

import com.squareup.moshi.Json

/**
 * 
 *
 * @param messages 
 * @param files 
 */


data class ChatSearchResponse (

    @Json(name = "messages")
    val messages: ChatSearchResultCategoryObj? = null,

    @Json(name = "files")
    val files: ChatSearchResultCategoryObj? = null

)

