/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.ChatInHistorySchema
import io.inappchat.sdk.models.ThreadResponse

import com.squareup.moshi.Json

/**
 * 
 *
 * @param total Total Chats in history under particular threadId.
 * @param chats List of history conversations
 * @param threads List of threads
 */


data class ChatSearchResultCategoryObj (

    /* Total Chats in history under particular threadId. */
    @Json(name = "total")
    val total: java.math.BigDecimal? = null,

    /* List of history conversations */
    @Json(name = "chats")
    val chats: kotlin.collections.List<ChatInHistorySchema>? = null,

    /* List of threads */
    @Json(name = "threads")
    val threads: kotlin.collections.List<ThreadResponse>? = null

)

