/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param threadId Thread ID
 * @param timestamp ISO Date
 */


data class ChatHistoryClearSchema (

    /* Thread ID */
    @Json(name = "threadId")
    val threadId: kotlin.String? = null,

    /* ISO Date */
    @Json(name = "timestamp")
    val timestamp: kotlin.String? = null

)

