/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param msgUniqueId Chat unique Identifier
 * @param emojiCode Emoje code string
 * @param action Reaction actionType. It can be set/clear
 * @param msgCorrelationId Client generated unique identifier used to trace message delivery till receiver.
 */


data class ChatReactionRequest (

    /* Chat unique Identifier */
    @Json(name = "msgUniqueId")
    val msgUniqueId: kotlin.String? = null,

    /* Emoje code string */
    @Json(name = "emojiCode")
    val emojiCode: kotlin.String? = null,

    /* Reaction actionType. It can be set/clear */
    @Json(name = "action")
    val action: kotlin.String? = null,

    /* Client generated unique identifier used to trace message delivery till receiver. */
    @Json(name = "msgCorrelationId")
    val msgCorrelationId: kotlin.String? = null

)

