/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * ertc User who reported the chat Report
 *
 * @param appUserId appUserId of user
 * @param eRTCUserId eRTC user ID of user
 * @param name name of user
 */


data class ChatReportSchemaReporterERTCUser (

    /* appUserId of user */
    @Json(name = "appUserId")
    val appUserId: kotlin.String? = null,

    /* eRTC user ID of user */
    @Json(name = "eRTCUserId")
    val eRTCUserId: kotlin.String? = null,

    /* name of user */
    @Json(name = "name")
    val name: kotlin.String? = null

)

