/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.ChatUserDetailsSchema

import com.squareup.moshi.Json

/**
 * 
 *
 * @param chatUserDetails List of chatUser details
 */


data class ChatUserDetailsResponse (

    /* List of chatUser details */
    @Json(name = "chatUserDetails")
    val chatUserDetails: kotlin.collections.List<ChatUserDetailsSchema>? = null

)

