/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param msgUniqueId Chat unique Identifier
 * @param emojiCode Emoje code string
 */


data class ChatReactionObj (

    /* Chat unique Identifier */
    @Json(name = "msgUniqueId")
    val msgUniqueId: kotlin.String? = null,

    /* Emoje code string */
    @Json(name = "emojiCode")
    val emojiCode: kotlin.String? = null

)

