/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param statusKeys list of status keys needed in response. Must contain atleast one item.
 * @param appUserIds appUserId list of chatUsers
 */


data class ChatUserDetailsRequest (

    /* list of status keys needed in response. Must contain atleast one item. */
    @Json(name = "statusKeys")
    val statusKeys: kotlin.collections.List<kotlin.String>? = null,

    /* appUserId list of chatUsers */
    @Json(name = "appUserIds")
    val appUserIds: kotlin.collections.List<kotlin.String>? = null

)

