/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.EmailContactSchema
import io.inappchat.sdk.models.NumberContactSchema

import com.squareup.moshi.Json

/**
 * 
 *
 * @param name Name of contact
 * @param numbers Contact Number
 * @param emails Contact Email
 */


data class ContactSchema (

    /* Name of contact */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* Contact Number */
    @Json(name = "numbers")
    val numbers: kotlin.collections.List<NumberContactSchema>? = null,

    /* Contact Email */
    @Json(name = "emails")
    val emails: kotlin.collections.List<EmailContactSchema>? = null

)

