/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param category Catgory of Chat Report possible values : other, abuse, spam, inappropriate
 * @param reason detailed reason for raising chat report
 */


data class CreateChatReport (

    /* Catgory of Chat Report possible values : other, abuse, spam, inappropriate */
    @Json(name = "category")
    val category: kotlin.String? = null,

    /* detailed reason for raising chat report */
    @Json(name = "reason")
    val reason: kotlin.String? = null

)

