/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.ChatObjIndeleteChatRequest

import com.squareup.moshi.Json

/**
 * 
 *
 * @param chats List of chat objects to be deleted. Required.
 * @param threadId Thread Id. Required.
 * @param deleteType type of delete. supported values: self/everyone. Required.
 * @param msgCorrelationId Client generated unique identifier used to trace message delivery till receiver.
 */


data class DeleteChatRequestObj (

    /* List of chat objects to be deleted. Required. */
    @Json(name = "chats")
    val chats: kotlin.collections.List<ChatObjIndeleteChatRequest>? = null,

    /* Thread Id. Required. */
    @Json(name = "threadId")
    val threadId: kotlin.String? = null,

    /* type of delete. supported values: self/everyone. Required. */
    @Json(name = "deleteType")
    val deleteType: kotlin.String? = null,

    /* Client generated unique identifier used to trace message delivery till receiver. */
    @Json(name = "msgCorrelationId")
    val msgCorrelationId: kotlin.String? = null

)

