/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.MentionSchema

import com.squareup.moshi.Json

/**
 * 
 *
 * @param msgUniqueId Unique identified of chat object generated by server
 * @param threadId Thread Id
 * @param tenantId Tenant Id
 * @param msgType message type. It can be text/image/video/gif/audio
 * @param createdAt Chat object creation epoch time in miliseconds
 * @param metadata JSON object which can be used for client reference in request/response context. Server will not do any processing on this object.
 * @param mentions 
 */


data class DraftResponse (

    /* Unique identified of chat object generated by server */
    @Json(name = "msgUniqueId")
    val msgUniqueId: kotlin.String? = null,

    /* Thread Id */
    @Json(name = "threadId")
    val threadId: kotlin.String? = null,

    /* Tenant Id */
    @Json(name = "tenantId")
    val tenantId: kotlin.String? = null,

    /* message type. It can be text/image/video/gif/audio */
    @Json(name = "msgType")
    val msgType: kotlin.String? = null,

    /* Chat object creation epoch time in miliseconds */
    @Json(name = "createdAt")
    val createdAt: java.math.BigDecimal? = null,

    /* JSON object which can be used for client reference in request/response context. Server will not do any processing on this object. */
    @Json(name = "metadata")
    val metadata: kotlin.Any? = null,

    @Json(name = "mentions")
    val mentions: kotlin.collections.List<MentionSchema>? = null

)

