/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param keyId Key identifier.
 * @param deviceId Device identifier.
 * @param publicKey public Key of associated device
 * @param eRTCUserId user eRTCUserId.
 */


data class E2eKeyObj (

    /* Key identifier. */
    @Json(name = "keyId")
    val keyId: kotlin.String? = null,

    /* Device identifier. */
    @Json(name = "deviceId")
    val deviceId: kotlin.String? = null,

    /* public Key of associated device */
    @Json(name = "publicKey")
    val publicKey: kotlin.String? = null,

    /* user eRTCUserId. */
    @Json(name = "eRTCUserId")
    val eRTCUserId: kotlin.String? = null

)

