/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.EditChatResponseChat

import com.squareup.moshi.Json

/**
 * 
 *
 * @param chat 
 */


data class EditChatResponse (

    @Json(name = "chat")
    val chat: EditChatResponseChat? = null

)

