/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.ReplyThreadSchemaChatRequest

import com.squareup.moshi.Json

/**
 * List of deleted chats
 *
 * @param msgUniqueId Chat unique Identifier
 * @param message message text. it can be present for any msgType value
 * @param isStarred If message is starred
 * @param replyThreadFeatureData 
 */


data class EditChatResponseChat (

    /* Chat unique Identifier */
    @Json(name = "msgUniqueId")
    val msgUniqueId: kotlin.String? = null,

    /* message text. it can be present for any msgType value */
    @Json(name = "message")
    val message: kotlin.String? = null,

    /* If message is starred */
    @Json(name = "isStarred")
    val isStarred: kotlin.Boolean? = null,

    @Json(name = "replyThreadFeatureData")
    val replyThreadFeatureData: ReplyThreadSchemaChatRequest? = null

)

