/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param type Type of Email contact. For example Home/Work
 * @param email Email
 */


data class EmailContactSchema (

    /* Type of Email contact. For example Home/Work */
    @Json(name = "type")
    val type: kotlin.String? = null,

    /* Email */
    @Json(name = "email")
    val email: kotlin.String? = null

)

