/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param keyId Key identifier.
 * @param deviceId Device identifier.
 * @param publicKey public Key of associated device
 * @param eRTCUserId user eRTCUserId.
 * @param message encrypted message text. it can be present for any msgType value
 * @param contact encrypted stringified contact object. please check contactSchema for object value
 * @param location encrypted stringified location object. please check contactSchema for object value
 * @param gify gify URL
 * @param path encrypted media path URL
 * @param thumbnail encrypted media thumbnail URL
 */


data class EncryptedMessage (

    /* Key identifier. */
    @Json(name = "keyId")
    val keyId: kotlin.String,

    /* Device identifier. */
    @Json(name = "deviceId")
    val deviceId: kotlin.String,

    /* public Key of associated device */
    @Json(name = "publicKey")
    val publicKey: kotlin.String? = null,

    /* user eRTCUserId. */
    @Json(name = "eRTCUserId")
    val eRTCUserId: kotlin.String? = null,

    /* encrypted message text. it can be present for any msgType value */
    @Json(name = "message")
    val message: kotlin.String? = null,

    /* encrypted stringified contact object. please check contactSchema for object value */
    @Json(name = "contact")
    val contact: kotlin.String? = null,

    /* encrypted stringified location object. please check contactSchema for object value */
    @Json(name = "location")
    val location: kotlin.String? = null,

    /* gify URL */
    @Json(name = "gify")
    val gify: kotlin.String? = null,

    /* encrypted media path URL */
    @Json(name = "path")
    val path: kotlin.String? = null,

    /* encrypted media thumbnail URL */
    @Json(name = "thumbnail")
    val thumbnail: kotlin.String? = null

)

