/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.EventMessage

import com.squareup.moshi.Json

/**
 * 
 *
 * @param eventType 
 * @param message 
 */


data class Event (

    @Json(name = "eventType")
    val eventType: Event.EventType? = null,

    @Json(name = "message")
    val message: EventMessage? = null

) {

    /**
     * 
     *
     * Values: userSelfUpdate,groupUpdated,chatReportUpdated,chatReaction,updateMessage,typingStatus,chat,msgReadStatus,availabilityStatus
     */
    enum class EventType(val value: kotlin.String) {
        @Json(name = "userSelfUpdate") userSelfUpdate("userSelfUpdate"),
        @Json(name = "groupUpdated") groupUpdated("groupUpdated"),
        @Json(name = "chatReportUpdated") chatReportUpdated("chatReportUpdated"),
        @Json(name = "chatReaction") chatReaction("chatReaction"),
        @Json(name = "updateMessage") updateMessage("updateMessage"),
        @Json(name = "typingStatus") typingStatus("typingStatus"),
        @Json(name = "chat") chat("chat"),
        @Json(name = "msgReadStatus") msgReadStatus("msgReadStatus"),
        @Json(name = "availabilityStatus") availabilityStatus("availabilityStatus");
    }
}

