/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.ReplyThreadSchemaChatRequest

import com.squareup.moshi.Json

/**
 * 
 *
 * @param eRTCUserId User unique Identifier
 * @param msgUniqueId Chat unique Identifier
 * @param emojiCode Emoje code string
 * @param action Reaction actionType. It can be set/clear
 * @param totalCount Total count of particular reaction with emojiCode
 * @param threadId Thread unique identifier
 * @param tenantId Tenant unique identifier
 * @param replyThreadFeatureData 
 * @param msgCorrelationId Client generated unique identifier used to trace message delivery till receiver.
 */


data class FcmMqttChatReaction (

    /* User unique Identifier */
    @Json(name = "eRTCUserId")
    val eRTCUserId: kotlin.String? = null,

    /* Chat unique Identifier */
    @Json(name = "msgUniqueId")
    val msgUniqueId: kotlin.String? = null,

    /* Emoje code string */
    @Json(name = "emojiCode")
    val emojiCode: kotlin.String? = null,

    /* Reaction actionType. It can be set/clear */
    @Json(name = "action")
    val action: kotlin.String? = null,

    /* Total count of particular reaction with emojiCode */
    @Json(name = "totalCount")
    val totalCount: java.math.BigDecimal? = null,

    /* Thread unique identifier */
    @Json(name = "threadId")
    val threadId: kotlin.String? = null,

    /* Tenant unique identifier */
    @Json(name = "tenantId")
    val tenantId: kotlin.String? = null,

    @Json(name = "replyThreadFeatureData")
    val replyThreadFeatureData: ReplyThreadSchemaChatRequest? = null,

    /* Client generated unique identifier used to trace message delivery till receiver. */
    @Json(name = "msgCorrelationId")
    val msgCorrelationId: kotlin.String? = null

)

