/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.UserSelfUpdateEventItem

import com.squareup.moshi.Json

/**
 * 
 *
 * @param eRTCUserId User's eRTCUserId
 * @param eventList 
 */


data class FcmMqttuserSelfUpdate (

    /* User's eRTCUserId */
    @Json(name = "eRTCUserId")
    val eRTCUserId: kotlin.String? = null,

    @Json(name = "eventList")
    val eventList: kotlin.collections.List<UserSelfUpdateEventItem>? = null

)

