/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.GroupUpdateEventUserDetails
import io.inappchat.sdk.models.GroupUpdatedEventItem

import com.squareup.moshi.Json

/**
 * 
 *
 * @param eventTriggeredByUser 
 * @param groupId Group ID with which event is related
 * @param threadId Thread ID of associated group
 * @param eventList 
 */


data class FcmMqttgroupUpdated (

    @Json(name = "eventTriggeredByUser")
    val eventTriggeredByUser: GroupUpdateEventUserDetails? = null,

    /* Group ID with which event is related */
    @Json(name = "groupId")
    val groupId: kotlin.String? = null,

    /* Thread ID of associated group */
    @Json(name = "threadId")
    val threadId: kotlin.String? = null,

    @Json(name = "eventList")
    val eventList: kotlin.collections.List<GroupUpdatedEventItem>? = null

)

