/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param fcmToken FCM Token
 * @param payload Refer https://firebase.google.com/docs/reference/admin/node/admin.messaging.Messaging#sendToDevice for possible values
 * @param options Refer https://firebase.google.com/docs/reference/admin/node/admin.messaging.Messaging#sendToDevice for possible values
 */


data class FcmValidationRequest (

    /* FCM Token */
    @Json(name = "fcmToken")
    val fcmToken: kotlin.String? = null,

    /* Refer https://firebase.google.com/docs/reference/admin/node/admin.messaging.Messaging#sendToDevice for possible values */
    @Json(name = "payload")
    val payload: kotlin.Any? = null,

    /* Refer https://firebase.google.com/docs/reference/admin/node/admin.messaging.Messaging#sendToDevice for possible values */
    @Json(name = "options")
    val options: kotlin.Any? = null

)

