/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.FreezeUnfreezeEventEventListInner

import com.squareup.moshi.Json

/**
 * Send when group is frozen or unfrozen
 *
 * @param groupId 
 * @param threadId 
 * @param eventList 
 */


data class FreezeUnfreezeEvent (

    @Json(name = "groupId")
    val groupId: kotlin.String? = null,

    @Json(name = "threadId")
    val threadId: kotlin.String? = null,

    @Json(name = "eventList")
    val eventList: kotlin.collections.List<FreezeUnfreezeEventEventListInner>? = null

)

