/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param eventType 
 */


data class FreezeUnfreezeEventEventListInner (

    @Json(name = "eventType")
    val eventType: FreezeUnfreezeEventEventListInner.EventType? = null

) {

    /**
     * 
     *
     * Values: frozen,unfrozen
     */
    enum class EventType(val value: kotlin.String) {
        @Json(name = "frozen") frozen("frozen"),
        @Json(name = "unfrozen") unfrozen("unfrozen");
    }
}

