/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.GetBlockedUsersResponseBlockedUsersInner

import com.squareup.moshi.Json

/**
 * 
 *
 * @param blockedUsers Blocked user list
 */


data class GetBlockedUsersResponse (

    /* Blocked user list */
    @Json(name = "blockedUsers")
    val blockedUsers: kotlin.collections.List<GetBlockedUsersResponseBlockedUsersInner>? = null

)

