/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param tenantId tenant Id
 * @param threadId Thread Id
 * @param message Message
 */


data class GetDraftSchema (

    /* tenant Id */
    @Json(name = "tenantId")
    val tenantId: kotlin.String? = null,

    /* Thread Id */
    @Json(name = "threadId")
    val threadId: kotlin.String? = null,

    /* Message */
    @Json(name = "message")
    val message: kotlin.String? = null

)

