/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.UserAuthPayload

import com.squareup.moshi.Json

/**
 * 
 *
 * @param appUserId User ID i.e. abc@def.com. Required. version=1:N
 * @param deviceId Unique device id. For example, UDID for ios. version=1:N
 * @param deviceType Type of device i.e. android or ios. Allowed valies android/ios. version=1:N
 * @param fcmToken FCM regsitration token. Optional. version=1:N
 * @param fcmVersion FCM Version. Optional. default value is f1. version=1:N
 * @param publicKey public key for end to end encryption. version=1:N
 * @param muteSetting Mute setting parameter. supported values - none / all / allbutmentions. version=1:N
 * @param authPayload 
 */


data class GetOrUpdateUserRequest (

    /* User ID i.e. abc@def.com. Required. version=1:N */
    @Json(name = "appUserId")
    val appUserId: kotlin.String? = null,

    /* Unique device id. For example, UDID for ios. version=1:N */
    @Json(name = "deviceId")
    val deviceId: kotlin.String? = null,

    /* Type of device i.e. android or ios. Allowed valies android/ios. version=1:N */
    @Json(name = "deviceType")
    val deviceType: kotlin.String? = null,

    /* FCM regsitration token. Optional. version=1:N */
    @Json(name = "fcmToken")
    val fcmToken: kotlin.String? = null,

    /* FCM Version. Optional. default value is f1. version=1:N */
    @Json(name = "fcmVersion")
    val fcmVersion: kotlin.String? = null,

    /* public key for end to end encryption. version=1:N */
    @Json(name = "publicKey")
    val publicKey: kotlin.String? = null,

    /* Mute setting parameter. supported values - none / all / allbutmentions. version=1:N */
    @Json(name = "muteSetting")
    val muteSetting: kotlin.String? = null,

    @Json(name = "authPayload")
    val authPayload: UserAuthPayload? = null

)

