/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.GetPendingEventsResponsePendingEventsInner

import com.squareup.moshi.Json

/**
 * 
 *
 * @param pendingEvents Pending event list. This is optional.
 */


data class GetPendingEventsResponse (

    /* Pending event list. This is optional. */
    @Json(name = "pendingEvents")
    val pendingEvents: kotlin.collections.List<GetPendingEventsResponsePendingEventsInner>? = null

)

