/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * event data
 *
 * @param eventType FCM event type
 * @param message Stringigied event message object
 */


data class GetPendingEventsResponsePendingEventsInnerData (

    /* FCM event type */
    @Json(name = "eventType")
    val eventType: kotlin.String? = null,

    /* Stringigied event message object */
    @Json(name = "message")
    val message: kotlin.String? = null

)

