/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.GroupUpdateEventChangeDataName

import com.squareup.moshi.Json

/**
 * 
 *
 * @param name 
 */


data class GroupUpdateEventChangeData (

    @Json(name = "name")
    val name: GroupUpdateEventChangeDataName? = null

)

