/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * Applicable for created/nameChanged/profilePicChanged/descriptionChanged eventTypes
 *
 * @param new new value
 * @param previous Previous value. Applicable only for nameChanged
 */


data class GroupUpdatEventChangeDataGroupType (

    /* new value */
    @Json(name = "new")
    val new: GroupUpdatEventChangeDataGroupType.New,

    /* Previous value. Applicable only for nameChanged */
    @Json(name = "previous")
    val previous: GroupUpdatEventChangeDataGroupType.Previous? = null

) {

    /**
     * new value
     *
     * Values: `public`,`private`
     */
    enum class New(val value: kotlin.String) {
        @Json(name = "public") `public`("public"),
        @Json(name = "private") `private`("private");
    }
    /**
     * Previous value. Applicable only for nameChanged
     *
     * Values: `public`,`private`
     */
    enum class Previous(val value: kotlin.String) {
        @Json(name = "public") `public`("public"),
        @Json(name = "private") `private`("private");
    }
}

