/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param eRTCUserId User's eRTCUserId
 * @param appUserId User's appUserId
 */


data class GroupUpdateEventUserDetails (

    /* User's eRTCUserId */
    @Json(name = "eRTCUserId")
    val eRTCUserId: kotlin.String? = null,

    /* User's appUserId */
    @Json(name = "appUserId")
    val appUserId: kotlin.String? = null

)

