/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.GroupUpdateEventData

import com.squareup.moshi.Json

/**
 * 
 *
 * @param eventType Type of the group event. it can be created/participantsAdded/participantsRemoved/nameChanged/profilePicChanged/descriptionChanged/profilePicRemoved/adminMade/adminDismissed
 * @param eventData 
 */


data class GroupUpdatedEventItem (

    /* Type of the group event. it can be created/participantsAdded/participantsRemoved/nameChanged/profilePicChanged/descriptionChanged/profilePicRemoved/adminMade/adminDismissed */
    @Json(name = "eventType")
    val eventType: kotlin.String? = null,

    @Json(name = "eventData")
    val eventData: GroupUpdateEventData? = null

)

