/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param name Group Name
 * @param groupType Type of group. for example privte/public. only private is supported as of now.
 * @param description Description of group. Optional. Min length 2.
 * @param participants List of participants
 */


data class GroupRequest (

    /* Group Name */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* Type of group. for example privte/public. only private is supported as of now. */
    @Json(name = "groupType")
    val groupType: kotlin.String? = null,

    /* Description of group. Optional. Min length 2. */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* List of participants */
    @Json(name = "participants")
    val participants: kotlin.collections.List<kotlin.String>? = null

)

