/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.GroupUpdateEventData

import com.squareup.moshi.Json

/**
 * Group update FCM event item
 *
 * @param eventType Type of the group event.
 * @param eventData 
 */


data class GroupUpdateEventItem (

    /* Type of the group event. */
    @Json(name = "eventType")
    val eventType: GroupUpdateEventItem.EventType,

    @Json(name = "eventData")
    val eventData: GroupUpdateEventData

) {

    /**
     * Type of the group event.
     *
     * Values: created,participantsAdded,participantsRemoved,nameChange,profilePicChanged,descriptionChanged,groupTypeChanged,profilePicRemoved,adminMade,adminDismissed
     */
    enum class EventType(val value: kotlin.String) {
        @Json(name = "created") created("created"),
        @Json(name = "participantsAdded") participantsAdded("participantsAdded"),
        @Json(name = "participantsRemoved") participantsRemoved("participantsRemoved"),
        @Json(name = "nameChange") nameChange("nameChange"),
        @Json(name = "profilePicChanged") profilePicChanged("profilePicChanged"),
        @Json(name = "descriptionChanged") descriptionChanged("descriptionChanged"),
        @Json(name = "groupTypeChanged") groupTypeChanged("groupTypeChanged"),
        @Json(name = "profilePicRemoved") profilePicRemoved("profilePicRemoved"),
        @Json(name = "adminMade") adminMade("adminMade"),
        @Json(name = "adminDismissed") adminDismissed("adminDismissed");
    }
}

