/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param appUserId appUserId of user
 * @param eRTCUserId eRTC user ID of user
 * @param role Role of participant. For example user/admin
 * @param joinedAtDate Time when user joined
 */


data class GroupParticipantSchema (

    /* appUserId of user */
    @Json(name = "appUserId")
    val appUserId: kotlin.String? = null,

    /* eRTC user ID of user */
    @Json(name = "eRTCUserId")
    val eRTCUserId: kotlin.String? = null,

    /* Role of participant. For example user/admin */
    @Json(name = "role")
    val role: kotlin.String? = null,

    /* Time when user joined */
    @Json(name = "joinedAtDate")
    val joinedAtDate: kotlin.String? = null

)

