/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.GroupUpdateEventChangeData
import io.inappchat.sdk.models.GroupUpdateEventUserDetails

import com.squareup.moshi.Json

/**
 * 
 *
 * @param eventTriggeredOnUserList Optional. Applicable for participantsAdded/participantsRemoved/adminMade/adminDismissed
 * @param changeData 
 */


data class GroupUpdateEventData (

    /* Optional. Applicable for participantsAdded/participantsRemoved/adminMade/adminDismissed */
    @Json(name = "eventTriggeredOnUserList")
    val eventTriggeredOnUserList: kotlin.collections.List<GroupUpdateEventUserDetails>? = null,

    @Json(name = "changeData")
    val changeData: GroupUpdateEventChangeData? = null

)

