/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.GroupHighLevelDetailsFreeze

import com.squareup.moshi.Json

/**
 * Group high level details
 *
 * @param groupId Group ID
 * @param name Group Name
 * @param groupType Type of group. for example privte/public. only private is supported as of now.
 * @param profilePic Profile pic url. use chatServer URL as prefix to generate complete URL 
 * @param profilePicThumb Profile pic thumbnail url. use chatServer URL as prefix to generate complete URL 
 * @param threadId ThreadId associated with group. To be used for chat
 * @param customConfig ThreadId associated with group. To be used for chat
 * @param freeze 
 */


data class GroupHighLevelDetails (

    /* Group ID */
    @Json(name = "groupId")
    val groupId: kotlin.String? = null,

    /* Group Name */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* Type of group. for example privte/public. only private is supported as of now. */
    @Json(name = "groupType")
    val groupType: kotlin.String? = null,

    /* Profile pic url. use chatServer URL as prefix to generate complete URL  */
    @Json(name = "profilePic")
    val profilePic: kotlin.String? = null,

    /* Profile pic thumbnail url. use chatServer URL as prefix to generate complete URL  */
    @Json(name = "profilePicThumb")
    val profilePicThumb: kotlin.String? = null,

    /* ThreadId associated with group. To be used for chat */
    @Json(name = "threadId")
    val threadId: kotlin.String? = null,

    /* ThreadId associated with group. To be used for chat */
    @Json(name = "customConfig")
    val customConfig: kotlin.Any? = null,

    @Json(name = "freeze")
    val freeze: GroupHighLevelDetailsFreeze? = null

)

