/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * Tells group frozen state
 *
 * @param enabled True means frozen
 */


data class GroupHighLevelDetailsFreeze (

    /* True means frozen */
    @Json(name = "enabled")
    val enabled: kotlin.Boolean? = null

)

