/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param groupId 
 * @param by 
 * @param to 
 * @param date 
 */


data class Invite (

    @Json(name = "groupId")
    val groupId: kotlin.String,

    @Json(name = "by")
    val by: kotlin.String,

    @Json(name = "to")
    val to: kotlin.String,

    @Json(name = "date")
    val date: kotlin.String

)

