/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param longitude Longitude
 * @param latitude Latitude
 * @param address Address of location
 */


data class LocationSchema (

    /* Longitude */
    @Json(name = "longitude")
    val longitude: java.math.BigDecimal? = null,

    /* Latitude */
    @Json(name = "latitude")
    val latitude: java.math.BigDecimal? = null,

    /* Address of location */
    @Json(name = "address")
    val address: kotlin.String? = null

)

