/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param loginType Type of login  like email/mobile/sso
 * @param appUserId User ID based on loginType
 * @param deviceId Unique device id. For example, UDID for ios
 * @param deviceType Type of device i.e. android or ios. Allowed valies android/ios
 * @param fcmToken FCM regsitration token. Optional.
 */


data class LoginInput (

    /* Type of login  like email/mobile/sso */
    @Json(name = "loginType")
    val loginType: LoginInput.LoginType,

    /* User ID based on loginType */
    @Json(name = "appUserId")
    val appUserId: kotlin.String,

    /* Unique device id. For example, UDID for ios */
    @Json(name = "deviceId")
    val deviceId: kotlin.String,

    /* Type of device i.e. android or ios. Allowed valies android/ios */
    @Json(name = "deviceType")
    val deviceType: LoginInput.DeviceType? = null,

    /* FCM regsitration token. Optional. */
    @Json(name = "fcmToken")
    val fcmToken: kotlin.String? = null

) {

    /**
     * Type of login  like email/mobile/sso
     *
     * Values: email,mobile,sso
     */
    enum class LoginType(val value: kotlin.String) {
        @Json(name = "email") email("email"),
        @Json(name = "mobile") mobile("mobile"),
        @Json(name = "sso") sso("sso");
    }
    /**
     * Type of device i.e. android or ios. Allowed valies android/ios
     *
     * Values: android,ios
     */
    enum class DeviceType(val value: kotlin.String) {
        @Json(name = "android") android("android"),
        @Json(name = "ios") ios("ios");
    }
}

