/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param appUserId User ID i.e. abc@def.com. Required.
 * @param deviceId Unique device id. For example, UDID for ios
 */


data class LogoutUserRequest (

    /* User ID i.e. abc@def.com. Required. */
    @Json(name = "appUserId")
    val appUserId: kotlin.String? = null,

    /* Unique device id. For example, UDID for ios */
    @Json(name = "deviceId")
    val deviceId: kotlin.String? = null

)

