/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * user object
 *
 * @param targetAppUserId appUserId of target user
 */


data class MakeDismissAdminPostRequest (

    /* appUserId of target user */
    @Json(name = "targetAppUserId")
    val targetAppUserId: kotlin.String? = null

)

