/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param path media URL. use chatServer URL as prefix to generate complete URL
 * @param thumbnail media thumbnail URL. It can be present for only media with msgType as 'image'. use chatServer URL as prefix to generate complete URL
 * @param name original name of file uploaded
 */


data class Media (

    /* media URL. use chatServer URL as prefix to generate complete URL */
    @Json(name = "path")
    val path: kotlin.String? = null,

    /* media thumbnail URL. It can be present for only media with msgType as 'image'. use chatServer URL as prefix to generate complete URL */
    @Json(name = "thumbnail")
    val thumbnail: kotlin.String? = null,

    /* original name of file uploaded */
    @Json(name = "name")
    val name: kotlin.String? = null

)

