/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param type 
 * @param `value` 
 */


data class Mention (

    @Json(name = "type")
    val type: kotlin.String? = null,

    @Json(name = "value")
    val `value`: kotlin.String? = null

)

