/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.APIMessage
import io.inappchat.sdk.models.ChatStatus

import com.squareup.moshi.Json

/**
 * 
 *
 * @param status 
 * @param message 
 */


data class MessageResponse (

    @Json(name = "status")
    val status: ChatStatus,

    @Json(name = "message")
    val message: APIMessage? = null

)

