/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * A message content type
 *
 * Values: text,image,audio,video,gif,file,contact,location
 */

enum class MessageType(val value: kotlin.String) {

    @Json(name = "text")
    text("text"),

    @Json(name = "image")
    image("image"),

    @Json(name = "audio")
    audio("audio"),

    @Json(name = "video")
    video("video"),

    @Json(name = "gif")
    gif("gif"),

    @Json(name = "file")
    file("file"),

    @Json(name = "contact")
    contact("contact"),

    @Json(name = "location")
    location("location");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is MessageType) "$data" else null

        /**
         * Returns a valid [MessageType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): MessageType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

