/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param participants 
 * @param type 
 * @param till 
 */


data class ModerateGroupInput (

    @Json(name = "participants")
    val participants: kotlin.collections.List<kotlin.String>,

    @Json(name = "type")
    val type: ModerateGroupInput.Type,

    @Json(name = "till")
    val till: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: ban,mute,unmute,unban
     */
    enum class Type(val value: kotlin.String) {
        @Json(name = "ban") ban("ban"),
        @Json(name = "mute") mute("mute"),
        @Json(name = "unmute") unmute("unmute"),
        @Json(name = "unban") unban("unban");
    }
}

