/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * A user updating a message read state
 *
 * @param msgUniqueId The ID of the message
 * @param eRTCUserId The ID of the user marking the message read
 * @param msgReadStatus The status of the message
 */


data class MsgReadEvent (

    /* The ID of the message */
    @Json(name = "msgUniqueId")
    val msgUniqueId: kotlin.String,

    /* The ID of the user marking the message read */
    @Json(name = "eRTCUserId")
    val eRTCUserId: kotlin.String,

    /* The status of the message */
    @Json(name = "msgReadStatus")
    val msgReadStatus: MsgReadEvent.MsgReadStatus

) {

    /**
     * The status of the message
     *
     * Values: delivered,seen
     */
    enum class MsgReadStatus(val value: kotlin.String) {
        @Json(name = "delivered") delivered("delivered"),
        @Json(name = "seen") seen("seen");
    }
}

