/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.APIMessage

import com.squareup.moshi.Json

/**
 * A new message
 *
 * @param message 
 */


data class NewMessageEvent (

    @Json(name = "message")
    val message: APIMessage

)

