/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.ChatUserDetailsSchemaStatusDetails

import com.squareup.moshi.Json

/**
 * individual chatUser details
 *
 * @param id unique id of user
 * @param appUserId appUserId of user
 * @param appState active, inactive, or deleted
 * @param eRTCUserId eRTC user ID of user
 * @param profilePic Url for profile picture
 * @param profileStatus user status
 * @param profilePicThumb user profile picture thumbnail url
 * @param loginTimeStamp last login time stamp
 * @param statusDetails 
 */


data class NFTLoginResponseSchema (

    /* unique id of user */
    @Json(name = "id")
    val id: kotlin.String? = null,

    /* appUserId of user */
    @Json(name = "appUserId")
    val appUserId: kotlin.String? = null,

    /* active, inactive, or deleted */
    @Json(name = "appState")
    val appState: kotlin.String? = null,

    /* eRTC user ID of user */
    @Json(name = "eRTCUserId")
    val eRTCUserId: kotlin.String? = null,

    /* Url for profile picture */
    @Json(name = "profilePic")
    val profilePic: kotlin.String? = null,

    /* user status */
    @Json(name = "profileStatus")
    val profileStatus: kotlin.String? = null,

    /* user profile picture thumbnail url */
    @Json(name = "profilePicThumb")
    val profilePicThumb: kotlin.String? = null,

    /* last login time stamp */
    @Json(name = "loginTimeStamp")
    val loginTimeStamp: java.math.BigDecimal? = null,

    @Json(name = "statusDetails")
    val statusDetails: ChatUserDetailsSchemaStatusDetails? = null

)

