/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param address wallet address of user
 * @param `contract` contract address of NFT
 * @param signature user wallet signature
 * @param tokenID token ID of NFT
 * @param username 
 * @param profilePicture The image to use as the user's profile picture
 */


data class NFTLoginInput (

    /* wallet address of user */
    @Json(name = "address")
    val address: kotlin.String,

    /* contract address of NFT */
    @Json(name = "contract")
    val `contract`: kotlin.String,

    /* user wallet signature */
    @Json(name = "signature")
    val signature: kotlin.String,

    /* token ID of NFT */
    @Json(name = "tokenID")
    val tokenID: kotlin.String,

    @Json(name = "username")
    val username: kotlin.String? = null,

    /* The image to use as the user's profile picture */
    @Json(name = "profilePicture")
    val profilePicture: kotlin.String? = null

)

