/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param type Type of Number contact. For example Home/Work
 * @param number Contact Number
 */


data class NumberContactSchema (

    /* Type of Number contact. For example Home/Work */
    @Json(name = "type")
    val type: kotlin.String? = null,

    /* Contact Number */
    @Json(name = "number")
    val number: kotlin.String? = null

)

