/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param emojiCode Emoje code string
 * @param count Emoje code string
 * @param users List of eRTCUserIds
 */


data class ReactionInChatHistorySchema (

    /* Emoje code string */
    @Json(name = "emojiCode")
    val emojiCode: kotlin.String? = null,

    /* Emoje code string */
    @Json(name = "count")
    val count: kotlin.String? = null,

    /* List of eRTCUserIds */
    @Json(name = "users")
    val users: kotlin.collections.List<kotlin.String>? = null

)

