/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param emojiCode 
 * @param count 
 * @param users 
 */


data class Reaction (

    @Json(name = "emojiCode")
    val emojiCode: kotlin.String,

    @Json(name = "count")
    val count: kotlin.Int,

    @Json(name = "users")
    val users: kotlin.collections.List<kotlin.String>

)

