/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param eRTCUserId User unique Identifier
 * @param msgUniqueId Chat unique Identifier
 * @param emojiCode Emoje code string
 * @param action Reaction actionType. It can be set/clear
 * @param totalCount Total count of particular reaction with emojiCode
 */


data class ReactionEvent (

    /* User unique Identifier */
    @Json(name = "eRTCUserId")
    val eRTCUserId: kotlin.String,

    /* Chat unique Identifier */
    @Json(name = "msgUniqueId")
    val msgUniqueId: kotlin.String,

    /* Emoje code string */
    @Json(name = "emojiCode")
    val emojiCode: kotlin.String,

    /* Reaction actionType. It can be set/clear */
    @Json(name = "action")
    val action: kotlin.String,

    /* Total count of particular reaction with emojiCode */
    @Json(name = "totalCount")
    val totalCount: java.math.BigDecimal

)

