/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * Return code associated with individual key object.
 *
 * Values: receiverKeyNotActive,receiverKeyInvalid,receiverNewDeviceKeyAvailable
 */

enum class ReceiverReturnCode(val value: kotlin.String) {

    @Json(name = "receiverKeyNotActive")
    receiverKeyNotActive("receiverKeyNotActive"),

    @Json(name = "receiverKeyInvalid")
    receiverKeyInvalid("receiverKeyInvalid"),

    @Json(name = "receiverNewDeviceKeyAvailable")
    receiverNewDeviceKeyAvailable("receiverNewDeviceKeyAvailable");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ReceiverReturnCode) "$data" else null

        /**
         * Returns a valid [ReceiverReturnCode] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ReceiverReturnCode? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

