/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param baseMsgUniqueId msgUniqueId of base chat
 * @param replyMsgConfig Reply config which applies to reply chat. For example, bit 0 is used to decide whether to show reply on window or not.
 */


data class ReplyThreadSchemaChatReceive (

    /* msgUniqueId of base chat */
    @Json(name = "baseMsgUniqueId")
    val baseMsgUniqueId: kotlin.String? = null,

    /* Reply config which applies to reply chat. For example, bit 0 is used to decide whether to show reply on window or not. */
    @Json(name = "replyMsgConfig")
    val replyMsgConfig: java.math.BigDecimal? = null

)

