/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param baseMsgUniqueId msgUniqueId of base chat
 */


data class ReplyThreadSchemaChatResponse (

    /* msgUniqueId of base chat */
    @Json(name = "baseMsgUniqueId")
    val baseMsgUniqueId: kotlin.String? = null

)

