/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.ThreadReplyReplies

import com.squareup.moshi.Json

/**
 * 
 *
 * @param replies 2 replies
 */


data class ReplyThreadResultSchemaAllOf (

    /* 2 replies */
    @Json(name = "replies")
    val replies: kotlin.collections.List<ThreadReplyReplies>? = null

)

