/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * Values: abuse,spam,other,inappropriate
 */

enum class ReportCategory(val value: kotlin.String) {

    @Json(name = "abuse")
    abuse("abuse"),

    @Json(name = "spam")
    spam("spam"),

    @Json(name = "other")
    other("other"),

    @Json(name = "inappropriate")
    inappropriate("inappropriate");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ReportCategory) "$data" else null

        /**
         * Returns a valid [ReportCategory] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ReportCategory? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

