/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.APIMessage
import io.inappchat.sdk.models.APIUser
import io.inappchat.sdk.models.ReportCategory
import io.inappchat.sdk.models.ReportChannelAdminStatus
import io.inappchat.sdk.models.ReportTenantAdminStatus

import com.squareup.moshi.Json

/**
 * 
 *
 * @param tenantId Tenant Id
 * @param category 
 * @param reason detailed reason for raising chat report
 * @param channelAdminStatus 
 * @param tenantAdminStatus 
 * @param reporterERTCUser 
 * @param chat 
 * @param chatReportId Chat Report ID
 */


data class Report (

    /* Tenant Id */
    @Json(name = "tenantId")
    val tenantId: kotlin.String,

    @Json(name = "category")
    val category: ReportCategory,

    /* detailed reason for raising chat report */
    @Json(name = "reason")
    val reason: kotlin.String,

    @Json(name = "channelAdminStatus")
    val channelAdminStatus: ReportChannelAdminStatus,

    @Json(name = "tenantAdminStatus")
    val tenantAdminStatus: ReportTenantAdminStatus,

    @Json(name = "reporterERTCUser")
    val reporterERTCUser: APIUser,

    @Json(name = "chat")
    val chat: APIMessage,

    /* Chat Report ID */
    @Json(name = "chatReportId")
    val chatReportId: kotlin.String? = null

)

