/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.ReportCategory
import io.inappchat.sdk.models.ReportStatus

import com.squareup.moshi.Json

/**
 * tenant Admin Status
 *
 * @param status 
 * @param category 
 * @param createdAt Chat Report Status creation epoch timeStamp
 */


data class ReportTenantAdminStatus (

    @Json(name = "status")
    val status: ReportStatus? = null,

    @Json(name = "category")
    val category: ReportCategory? = null,

    /* Chat Report Status creation epoch timeStamp */
    @Json(name = "createdAt")
    val createdAt: java.math.BigDecimal? = null

)

