/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param loginType Type of login like email/mobile/sso
 * @param appUserId User ID based on loginType
 */


data class ResetPasswordInput (

    /* Type of login like email/mobile/sso */
    @Json(name = "loginType")
    val loginType: kotlin.String,

    /* User ID based on loginType */
    @Json(name = "appUserId")
    val appUserId: kotlin.String

)

