/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param returnCode Return code associated with individual key object.
 */


data class ReturnCode (

    /* Return code associated with individual key object. */
    @Json(name = "returnCode")
    val returnCode: ReturnCode.ReturnCode? = null

) {

    /**
     * Return code associated with individual key object.
     *
     * Values: receiverKeyNotActive,receiverKeyInvalid,receiverNewDeviceKeyAvailable
     */
    enum class ReturnCode(val value: kotlin.String) {
        @Json(name = "receiverKeyNotActive") receiverKeyNotActive("receiverKeyNotActive"),
        @Json(name = "receiverKeyInvalid") receiverKeyInvalid("receiverKeyInvalid"),
        @Json(name = "receiverNewDeviceKeyAvailable") receiverNewDeviceKeyAvailable("receiverNewDeviceKeyAvailable");
    }
}

