/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.ReceiverReturnCode

import com.squareup.moshi.Json

/**
 * 
 *
 * @param returnCode 
 */


data class ReturnCode (

    @Json(name = "returnCode")
    val returnCode: ReceiverReturnCode? = null

)

