/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.APIGroup
import io.inappchat.sdk.models.APIMessage

import com.squareup.moshi.Json

/**
 * 
 *
 * @param messages 
 * @param files 
 * @param channels 
 */


data class SearchResults (

    @Json(name = "messages")
    val messages: kotlin.collections.List<APIMessage>? = null,

    @Json(name = "files")
    val files: kotlin.collections.List<APIMessage>? = null,

    @Json(name = "channels")
    val channels: kotlin.collections.List<APIGroup>? = null

)

