/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.UserSelfUpdateEventData

import com.squareup.moshi.Json

/**
 * 
 *
 * @param eventType Type of the event.
 * @param eventData 
 */


data class SelfUpdateItem (

    /* Type of the event. */
    @Json(name = "eventType")
    val eventType: SelfUpdateItem.EventType,

    @Json(name = "eventData")
    val eventData: UserSelfUpdateEventData

) {

    /**
     * Type of the event.
     *
     * Values: availabilityStatusChanged,notificationSettingChangedGlobal,notificationSettingsChangedThread,userBlockedStatusChanged
     */
    enum class EventType(val value: kotlin.String) {
        @Json(name = "availabilityStatusChanged") availabilityStatusChanged("availabilityStatusChanged"),
        @Json(name = "notificationSettingChangedGlobal") notificationSettingChangedGlobal("notificationSettingChangedGlobal"),
        @Json(name = "notificationSettingsChangedThread") notificationSettingsChangedThread("notificationSettingsChangedThread"),
        @Json(name = "userBlockedStatusChanged") userBlockedStatusChanged("userBlockedStatusChanged");
    }
}

