/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * Sender key details used for this chat.
 *
 * @param keyId Key identifier. This is optional. If it is not provided, means this publice key needs to be registerd.
 * @param deviceId Device identifier.
 * @param publicKey public Key of associated device
 */


data class SenderKeyDetails (

    /* Key identifier. This is optional. If it is not provided, means this publice key needs to be registerd. */
    @Json(name = "keyId")
    val keyId: kotlin.String,

    /* Device identifier. */
    @Json(name = "deviceId")
    val deviceId: kotlin.String,

    /* public Key of associated device */
    @Json(name = "publicKey")
    val publicKey: kotlin.String

)

