/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param eRTCUserId eRTC user Id
 * @param appUserId User ID i.e. abc@def.com
 * @param name User name
 */


data class SenderInChatEventSubscribe (

    /* eRTC user Id */
    @Json(name = "eRTCUserId")
    val eRTCUserId: kotlin.String? = null,

    /* User ID i.e. abc@def.com */
    @Json(name = "appUserId")
    val appUserId: kotlin.String? = null,

    /* User name */
    @Json(name = "name")
    val name: kotlin.String? = null

)

