/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.SenderKeyDetails

import com.squareup.moshi.Json

/**
 * This does not exist
 *
 * @param senderKeyDetails 
 */


data class Stub (

    @Json(name = "senderKeyDetails")
    val senderKeyDetails: SenderKeyDetails? = null

)

