/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param sendereRTCUserId eRTC user id of source user
 * @param recipientAppUserId App user Id of receiver
 */


data class ThreadRequest (

    /* eRTC user id of source user */
    @Json(name = "sendereRTCUserId")
    val sendereRTCUserId: kotlin.String? = null,

    /* App user Id of receiver */
    @Json(name = "recipientAppUserId")
    val recipientAppUserId: kotlin.String? = null

)

