/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.ThreadObject

import com.squareup.moshi.Json

/**
 * 
 *
 * @param thread 
 */


data class ThreadInHistoryV2Schema (

    @Json(name = "thread")
    val thread: ThreadObject? = null

)

