/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.AutoDeleteSetting
import io.inappchat.sdk.models.NotificationSettings

import com.squareup.moshi.Json

/**
 * 
 *
 * @param user eRTC user Id of member
 * @param notificationSettings 
 * @param autoDeleteSetting 
 */


data class ThreadMemberSchema (

    /* eRTC user Id of member */
    @Json(name = "user")
    val user: kotlin.String? = null,

    @Json(name = "notificationSettings")
    val notificationSettings: NotificationSettings? = null,

    @Json(name = "autoDeleteSetting")
    val autoDeleteSetting: AutoDeleteSetting? = null

)

