/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.ReactionInChatHistorySchema
import io.inappchat.sdk.models.ReplyThreadSchemaChatRequest

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id uniqueId of the first reply messageL
 * @param threadId Id of the thread
 * @param message text sent in message
 * @param msgType type of message
 * @param sendereRTCUserId Sender eRTCUserId of message
 * @param replyThreadFeatureData 
 * @param senderTimeStampMs epoch timestamp (in ms) of message creation generated on sender device
 * @param tenantId Tenant Id
 * @param isEdited If chat message is starred
 * @param reactions list of reactions
 */


data class ThreadReplyReplies (

    /* uniqueId of the first reply messageL */
    @Json(name = "_id")
    val id: kotlin.String? = null,

    /* Id of the thread */
    @Json(name = "threadId")
    val threadId: kotlin.String? = null,

    /* text sent in message */
    @Json(name = "message")
    val message: kotlin.String? = null,

    /* type of message */
    @Json(name = "msgType")
    val msgType: kotlin.String? = null,

    /* Sender eRTCUserId of message */
    @Json(name = "sendereRTCUserId")
    val sendereRTCUserId: kotlin.String? = null,

    @Json(name = "replyThreadFeatureData")
    val replyThreadFeatureData: ReplyThreadSchemaChatRequest? = null,

    /* epoch timestamp (in ms) of message creation generated on sender device */
    @Json(name = "senderTimeStampMs")
    val senderTimeStampMs: java.math.BigDecimal? = null,

    /* Tenant Id */
    @Json(name = "tenantId")
    val tenantId: kotlin.String? = null,

    /* If chat message is starred */
    @Json(name = "isEdited")
    val isEdited: kotlin.Boolean? = null,

    /* list of reactions */
    @Json(name = "reactions")
    val reactions: kotlin.collections.List<ReactionInChatHistorySchema>? = null

)

