/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.ThreadInHistorySchema

import com.squareup.moshi.Json

/**
 * 
 *
 * @param total Total conversations in history with matching threadType.
 * @param threads List of history conversations
 */


data class ThreadHistoryResponseSchema (

    /* Total conversations in history with matching threadType. */
    @Json(name = "total")
    val total: java.math.BigDecimal? = null,

    /* List of history conversations */
    @Json(name = "threads")
    val threads: kotlin.collections.List<ThreadInHistorySchema>? = null

)

