/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param accessToken Access token to be provided in all API calls
 * @param refreshToken Refresh token
 * @param expiresIn The interval in seconds over which token is valid
 */


data class Token (

    /* Access token to be provided in all API calls */
    @Json(name = "accessToken")
    val accessToken: kotlin.String,

    /* Refresh token */
    @Json(name = "refreshToken")
    val refreshToken: kotlin.String,

    /* The interval in seconds over which token is valid */
    @Json(name = "expiresIn")
    val expiresIn: java.math.BigDecimal

)

