/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param tenantId Unique identified tenant
 * @param participants Array of thread participant eRTCUserId except sender
 * @param threadId Unique identified Thread
 * @param eRTCUserId User's eRTCUserId who pubblished this topic
 * @param typingStatusEvent Typing status event type : on/off
 * @param threadType Thread group : single/group
 * @param msgCorrelationId Client generated unique identifier used to trace message delivery till receiver.
 */


data class TypingStatusEventPublish (

    /* Unique identified tenant */
    @Json(name = "tenantId")
    val tenantId: kotlin.String? = null,

    /* Array of thread participant eRTCUserId except sender */
    @Json(name = "participants")
    val participants: kotlin.collections.List<kotlin.String>? = null,

    /* Unique identified Thread */
    @Json(name = "threadId")
    val threadId: kotlin.String? = null,

    /* User's eRTCUserId who pubblished this topic */
    @Json(name = "eRTCUserId")
    val eRTCUserId: kotlin.String? = null,

    /* Typing status event type : on/off */
    @Json(name = "typingStatusEvent")
    val typingStatusEvent: kotlin.String? = null,

    /* Thread group : single/group */
    @Json(name = "threadType")
    val threadType: kotlin.String? = null,

    /* Client generated unique identifier used to trace message delivery till receiver. */
    @Json(name = "msgCorrelationId")
    val msgCorrelationId: kotlin.String? = null

)

