/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * A user's typing status change in a chat
 *
 * @param eRTCUserId The user sending the typing status
 * @param typingStatusEvent Whether or not the user is typing
 * @param appUserId The user receiving the typing status
 * @param groupId The group receiving the typing status
 */


data class TypingEvent (

    /* The user sending the typing status */
    @Json(name = "eRTCUserId")
    val eRTCUserId: kotlin.String,

    /* Whether or not the user is typing */
    @Json(name = "typingStatusEvent")
    val typingStatusEvent: TypingEvent.TypingStatusEvent,

    /* The user receiving the typing status */
    @Json(name = "appUserId")
    val appUserId: kotlin.String? = null,

    /* The group receiving the typing status */
    @Json(name = "groupId")
    val groupId: kotlin.String? = null

) {

    /**
     * Whether or not the user is typing
     *
     * Values: on,off
     */
    enum class TypingStatusEvent(val value: kotlin.String) {
        @Json(name = "on") on("on"),
        @Json(name = "off") off("off");
    }
}

