/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param tenantId Unique identified tenant
 * @param threadId Unique identified Thread
 * @param eRTCUserId User's eRTCUserId who pubblished this topic
 * @param typingStatusEvent Typing status event type : on/off
 * @param name Name of the user typing. This needs to be populated from source device.
 * @param msgCorrelationId Client generated unique identifier used to trace message delivery till receiver.
 */


data class TypingStatusEventSubscribe (

    /* Unique identified tenant */
    @Json(name = "tenantId")
    val tenantId: kotlin.String? = null,

    /* Unique identified Thread */
    @Json(name = "threadId")
    val threadId: kotlin.String? = null,

    /* User's eRTCUserId who pubblished this topic */
    @Json(name = "eRTCUserId")
    val eRTCUserId: kotlin.String? = null,

    /* Typing status event type : on/off */
    @Json(name = "typingStatusEvent")
    val typingStatusEvent: kotlin.String? = null,

    /* Name of the user typing. This needs to be populated from source device. */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* Client generated unique identifier used to trace message delivery till receiver. */
    @Json(name = "msgCorrelationId")
    val msgCorrelationId: kotlin.String? = null

)

