/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.ChannelQueryObj

import com.squareup.moshi.Json

/**
 * 
 *
 * @param text Query string. Reuiqred.
 * @param threadId Thread Id if search target is particular thread. optional.
 * @param channelQuery 
 */


data class UnifiedSearchSearchQuery (

    /* Query string. Reuiqred. */
    @Json(name = "text")
    val text: kotlin.String? = null,

    /* Thread Id if search target is particular thread. optional. */
    @Json(name = "threadId")
    val threadId: kotlin.String? = null,

    @Json(name = "channelQuery")
    val channelQuery: ChannelQueryObj? = null

)

