/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.UnifiedSearchSearchQuery

import com.squareup.moshi.Json

/**
 * 
 *
 * @param searchQuery 
 * @param resultCategories Result category list
 */


data class UnifiedSearchRequest (

    @Json(name = "searchQuery")
    val searchQuery: UnifiedSearchSearchQuery? = null,

    /* Result category list */
    @Json(name = "resultCategories")
    val resultCategories: kotlin.collections.List<UnifiedSearchRequest.ResultCategories>? = null

) {

    /**
     * Result category list
     *
     * Values: messages,files,channels
     */
    enum class ResultCategories(val value: kotlin.String) {
        @Json(name = "messages") messages("messages"),
        @Json(name = "files") files("files"),
        @Json(name = "channels") channels("channels");
    }
}

