/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.AvailabilityStatus
import io.inappchat.sdk.models.NotificationSettings

import com.squareup.moshi.Json

/**
 * 
 *
 * @param deviceId Unique device id. For example, UDID for ios
 * @param deviceType Type of device
 * @param fcmToken FCM regsitration token. Optional.
 * @param fcmVersion FCM Version. Optional. default value is f1
 * @param availabilityStatus 
 * @param notificationSettings 
 * @param displayName Display name for user
 * @param username username. min length of 5 char
 * @param phoneNumber e164 format phone number
 */


data class UpdateUserInput (

    /* Unique device id. For example, UDID for ios */
    @Json(name = "deviceId")
    val deviceId: kotlin.String? = null,

    /* Type of device */
    @Json(name = "deviceType")
    val deviceType: UpdateUserInput.DeviceType? = null,

    /* FCM regsitration token. Optional. */
    @Json(name = "fcmToken")
    val fcmToken: kotlin.String? = null,

    /* FCM Version. Optional. default value is f1 */
    @Json(name = "fcmVersion")
    val fcmVersion: kotlin.String? = null,

    @Json(name = "availabilityStatus")
    val availabilityStatus: AvailabilityStatus? = null,

    @Json(name = "notificationSettings")
    val notificationSettings: NotificationSettings? = null,

    /* Display name for user */
    @Json(name = "displayName")
    val displayName: kotlin.String? = null,

    /* username. min length of 5 char */
    @Json(name = "username")
    val username: kotlin.String? = null,

    /* e164 format phone number */
    @Json(name = "phoneNumber")
    val phoneNumber: kotlin.String? = null

) {

    /**
     * Type of device
     *
     * Values: android,ios
     */
    enum class DeviceType(val value: kotlin.String) {
        @Json(name = "android") android("android"),
        @Json(name = "ios") ios("ios");
    }
}

