/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.NotificationSettings

import com.squareup.moshi.Json

/**
 * 
 *
 * @param deviceId Unique device id. For example, UDID for ios
 * @param deviceType Type of device i.e. android or ios. Allowed valies android/ios
 * @param fcmToken FCM regsitration token. Optional.
 * @param fcmVersion FCM Version. Optional. default value is f1
 * @param availabilityStatus availability status to be over-riden on top of default behaviour. i.e. auto/away/invisible/dnd
 * @param notificationSettings 
 */


data class UpdateUserRequest (

    /* Unique device id. For example, UDID for ios */
    @Json(name = "deviceId")
    val deviceId: kotlin.String? = null,

    /* Type of device i.e. android or ios. Allowed valies android/ios */
    @Json(name = "deviceType")
    val deviceType: kotlin.String? = null,

    /* FCM regsitration token. Optional. */
    @Json(name = "fcmToken")
    val fcmToken: kotlin.String? = null,

    /* FCM Version. Optional. default value is f1 */
    @Json(name = "fcmVersion")
    val fcmVersion: kotlin.String? = null,

    /* availability status to be over-riden on top of default behaviour. i.e. auto/away/invisible/dnd */
    @Json(name = "availabilityStatus")
    val availabilityStatus: kotlin.String? = null,

    @Json(name = "notificationSettings")
    val notificationSettings: NotificationSettings? = null

)

