/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param message message text. it can be present for any msgType value
 * @param isStarred If message is starred
 * @param follow Follow/unfollow thread
 */


data class UpdateMessageInput (

    /* message text. it can be present for any msgType value */
    @Json(name = "message")
    val message: kotlin.String? = null,

    /* If message is starred */
    @Json(name = "isStarred")
    val isStarred: kotlin.Boolean? = null,

    /* Follow/unfollow thread */
    @Json(name = "follow")
    val follow: kotlin.Boolean? = null

)

