/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.AutoDeleteSettings
import io.inappchat.sdk.models.NotificationSettings

import com.squareup.moshi.Json

/**
 * 
 *
 * @param notificationSettings 
 * @param autoDeleteSetting 
 */


data class UpdateThreadInput (

    @Json(name = "notificationSettings")
    val notificationSettings: NotificationSettings? = null,

    @Json(name = "autoDeleteSetting")
    val autoDeleteSetting: AutoDeleteSettings? = null

)

