/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * Chat update notification. It can be used for delete, edit etc. FCM event name - chatUpdate, MQTT Topic - chatUpdate:<clientId>
 *
 * @param eRTCUserId User unique Identifier
 * @param msgUniqueId Chat unique Identifier
 * @param updateType Type of update. 
 * @param deleteType in case of delete updateType, it specifies sub-type of delete such as self/everyone
 */


data class UpdateMessageEvent (

    /* User unique Identifier */
    @Json(name = "eRTCUserId")
    val eRTCUserId: kotlin.String,

    /* Chat unique Identifier */
    @Json(name = "msgUniqueId")
    val msgUniqueId: kotlin.String,

    /* Type of update.  */
    @Json(name = "updateType")
    val updateType: UpdateMessageEvent.UpdateType,

    /* in case of delete updateType, it specifies sub-type of delete such as self/everyone */
    @Json(name = "deleteType")
    val deleteType: UpdateMessageEvent.DeleteType

) {

    /**
     * Type of update. 
     *
     * Values: delete,edit
     */
    enum class UpdateType(val value: kotlin.String) {
        @Json(name = "delete") delete("delete"),
        @Json(name = "edit") edit("edit");
    }
    /**
     * in case of delete updateType, it specifies sub-type of delete such as self/everyone
     *
     * Values: self,everyone
     */
    enum class DeleteType(val value: kotlin.String) {
        @Json(name = "self") self("self"),
        @Json(name = "everyone") everyone("everyone");
    }
}

