/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.APIUser
import io.inappchat.sdk.models.AvailabilityStatus
import io.inappchat.sdk.models.NotificationSettings

import com.squareup.moshi.Json

/**
 * 
 *
 * @param threadId Optional. Thread id only applicable for notificationSettingsChangedThread
 * @param notificationSettings 
 * @param availabilityStatus 
 * @param blockedStatus Optional. Only applicable for userBlockedStatusChanged. Blocked status i.e. blocked/unblocked
 * @param targetUser 
 */


data class UserSelfUpdateEventData (

    /* Optional. Thread id only applicable for notificationSettingsChangedThread */
    @Json(name = "threadId")
    val threadId: kotlin.String? = null,

    @Json(name = "notificationSettings")
    val notificationSettings: NotificationSettings? = null,

    @Json(name = "availabilityStatus")
    val availabilityStatus: AvailabilityStatus? = null,

    /* Optional. Only applicable for userBlockedStatusChanged. Blocked status i.e. blocked/unblocked */
    @Json(name = "blockedStatus")
    val blockedStatus: UserSelfUpdateEventData.BlockedStatus? = null,

    @Json(name = "targetUser")
    val targetUser: APIUser? = null

) {

    /**
     * Optional. Only applicable for userBlockedStatusChanged. Blocked status i.e. blocked/unblocked
     *
     * Values: blocked,unblocked
     */
    enum class BlockedStatus(val value: kotlin.String) {
        @Json(name = "blocked") blocked("blocked"),
        @Json(name = "unblocked") unblocked("unblocked");
    }
}

