/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.GroupHighLevelDetails

import com.squareup.moshi.Json

/**
 * 
 *
 * @param groups Group list list
 */


data class UserGroupsResponse (

    /* Group list list */
    @Json(name = "groups")
    val groups: kotlin.collections.List<GroupHighLevelDetails>? = null

)

