/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * Applicable only for single threaType.
 *
 * @param eRTCUserId eRTC user Id of member
 * @param appUserId appUserId of member
 * @param name name of member
 * @param availabilityStatus availability status of user. i.e. online/away/invisible/dnd
 */


data class UserInThreadHistorySchema (

    /* eRTC user Id of member */
    @Json(name = "eRTCUserId")
    val eRTCUserId: kotlin.String? = null,

    /* appUserId of member */
    @Json(name = "appUserId")
    val appUserId: kotlin.String? = null,

    /* name of member */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* availability status of user. i.e. online/away/invisible/dnd */
    @Json(name = "availabilityStatus")
    val availabilityStatus: kotlin.String? = null

)

