/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.UserSelfUpdateEventData

import com.squareup.moshi.Json

/**
 * 
 *
 * @param eventType Type of the event. it can be availabilityStatusChanged / notificationSettingsChangedGlobal / notificationSettingsChangedThread / userBlockedStatusChanged 
 * @param eventData 
 */


data class UserSelfUpdateEventItem (

    /* Type of the event. it can be availabilityStatusChanged / notificationSettingsChangedGlobal / notificationSettingsChangedThread / userBlockedStatusChanged  */
    @Json(name = "eventType")
    val eventType: kotlin.String? = null,

    @Json(name = "eventData")
    val eventData: UserSelfUpdateEventData? = null

)

