/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.BaseMsgResponderSchema
import io.inappchat.sdk.models.NotificationSettings

import com.squareup.moshi.Json

/**
 * 
 *
 * @param threadId Optional. Thread id only applicable for notificationSettingsChangedThread
 * @param notificationSettings 
 * @param availabilityStatus Optional. Only applicable for availabilityStatusChanged. Availability status i.e. online/away/invisible/dnd
 * @param blockedStatus Optional. Only applicable for userBlockedStatusChanged. Blocked status i.e. blocked/unblocked
 * @param targetUser 
 */


data class UserSelfUpdateEventData (

    /* Optional. Thread id only applicable for notificationSettingsChangedThread */
    @Json(name = "threadId")
    val threadId: kotlin.String? = null,

    @Json(name = "notificationSettings")
    val notificationSettings: NotificationSettings? = null,

    /* Optional. Only applicable for availabilityStatusChanged. Availability status i.e. online/away/invisible/dnd */
    @Json(name = "availabilityStatus")
    val availabilityStatus: kotlin.String? = null,

    /* Optional. Only applicable for userBlockedStatusChanged. Blocked status i.e. blocked/unblocked */
    @Json(name = "blockedStatus")
    val blockedStatus: kotlin.String? = null,

    @Json(name = "targetUser")
    val targetUser: BaseMsgResponderSchema? = null

)

