/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models

import io.inappchat.sdk.models.UserAuthPayloadDataVersion2N

import com.squareup.moshi.Json

/**
 * 
 *
 * @param `data` 
 */


data class UserAuthPayload (

    @Json(name = "data")
    val `data`: UserAuthPayloadDataVersion2N? = null

)

