/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.inappchat.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param params 
 * @param header 
 * @param body 
 * @param query 
 */


data class UserAuthPayloadDataVersion2N (

    @Json(name = "params")
    val params: kotlin.Any? = null,

    @Json(name = "header")
    val header: kotlin.Any? = null,

    @Json(name = "body")
    val body: kotlin.Any? = null,

    @Json(name = "query")
    val query: kotlin.Any? = null

)

