# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sample-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  platform :ios, '15.0'

  pod 'BotStacks_ChatSDK', :path => "../../../chat-sdk"
end

